# Generated by Django 4.2.30 on 2026-05-21 22:46

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_created_at_profile_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 5, 21, 22, 46, 35, 218031, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
